In [46]:
import numpy as np
from gcimpute.helper_evaluation import get_smae
from gcimpute.gaussian_copula import GaussianCopula
from vcimpute.helper_datagen import make_complete_data_matrix, mask_MCAR

In [47]:
X = make_complete_data_matrix(1000, 5,'gaussian',seed=1)

In [48]:
X_mis = mask_MCAR(X, 'general', mask_frac=0.2, seed=1)

In [49]:
cop = GaussianCopula()
X_imp = cop.fit_transform(X_mis)

In [50]:
np.mean(get_smae(X_imp, X, X_mis))

0.6403765957102953

In [43]:
cop.sample_imputation?

In [57]:
X_mis

array([[0.08614976, 0.45792556, 0.57842989, 0.40389887, 0.56055436],
       [0.57587862, 0.60825491, 0.23541011, 0.24640224, 0.36782704],
       [       nan, 0.55782556,        nan, 0.65505927, 0.75488677],
       ...,
       [0.69710546, 0.05108624, 0.95522378, 0.62137791,        nan],
       [0.83227832, 0.78643521,        nan, 0.96580871, 0.13767796],
       [0.80699903,        nan, 0.70881685, 0.92214362, 0.42980842]])

In [58]:
from scipy.stats import norm

In [60]:
norm.cdf(cop._latent_Zimp[:,0])[-5:]

array([0.79525348, 0.93251534, 0.69079755, 0.82331288, 0.8       ])

In [80]:
X_imp = norm.cdf(cop._latent_Zimp)

In [74]:
cop._sample_latent(cop._latent_Zimp, cop._Z_ord_lower, cop._Z_ord_upper, 1)[...,0]

array([[6.94551107e-310, 2.14267093e-314, 2.69384353e-319,
                    nan, 3.59534816e+246],
       [1.75631032e-152, 3.17058865e+180, 8.44747281e+252,
        5.28400063e+005, 1.15476817e-259],
       [6.19962459e+223, 1.39647039e+228, 6.01346953e-154,
        2.13776925e+161, 1.19273052e+180],
       ...,
       [9.10434163e+276, 9.38185659e-154, 2.16401696e-027,
        1.81783298e+185, 1.42716889e+248],
       [1.42734010e+228, 1.22681370e-259, 1.99611597e+161,
        1.44529796e+166, 1.06185660e-153],
       [1.96871856e-153, 2.25064919e-153, 3.02880389e-086,
        4.81433988e+199, 1.92220079e+227]])

array([[-1.46716459, -0.13045996,  0.08616427, -0.31205332,  0.15274643],
       [ 0.18403279,  0.2566249 , -0.76890861, -0.77219321, -0.34724068],
       [-0.24976304,  0.13045996,  0.12862592,  0.38532047,  0.72559823],
       ...,
       [ 0.49811228, -1.58079879,  1.7965349 ,  0.28584087, -0.30167423],
       [ 0.92806427,  0.77133848, -0.15531628,  1.84525812, -1.16182481],
       [ 0.84162123, -0.24498877,  0.48635343,  1.41352982, -0.15274643]])

In [55]:
dir(cop)

['_Z_ord_lower',
 '_Z_ord_upper',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_batch_size',
 '_cont_indices',
 '_corr',
 '_corr_diff_type',
 '_decay',
 '_em_step',
 '_fillup_latent',
 '_fit_covariance',
 '_get_cond_std_missing',
 '_get_scaled_diff',
 '_init_Z_ord',
 '_init_copula_corr',
 '_iter',
 '_latent_Cord',
 '_latent_Zimp',
 '_latent_to_imp',
 '_max_iter',
 '_max_workers',
 '_min_ord_ratio',
 '_num_ord_updates',
 '_num_pass',
 '_observed_to_latent',
 '_ord_indices',
 '_preprocess_data',
 '_project_to_correlation',
 '_realtime_marginal',
 '_rng',
 '_sample_latent',
 '_sample_seed',
 '_seed',
 '_set_n_iter',
 '_threshold',
 '_training_mode',
 '_update_corr_dif

In [54]:
cop.latent_Zimp

AttributeError: 'GaussianCopula' object has no attribute 'latent_Zimp'

In [51]:
tmp = cop.sample_imputation(X_mis)

In [52]:
tmp

array([[[0.08614976, 0.08614976, 0.08614976, 0.08614976, 0.08614976],
        [0.45792556, 0.45792556, 0.45792556, 0.45792556, 0.45792556],
        [0.57842989, 0.57842989, 0.57842989, 0.57842989, 0.57842989],
        [0.40389887, 0.40389887, 0.40389887, 0.40389887, 0.40389887],
        [0.56055436, 0.56055436, 0.56055436, 0.56055436, 0.56055436]],

       [[0.57587862, 0.57587862, 0.57587862, 0.57587862, 0.57587862],
        [0.60825491, 0.60825491, 0.60825491, 0.60825491, 0.60825491],
        [0.23541011, 0.23541011, 0.23541011, 0.23541011, 0.23541011],
        [0.24640224, 0.24640224, 0.24640224, 0.24640224, 0.24640224],
        [0.36782704, 0.36782704, 0.36782704, 0.36782704, 0.36782704]],

       [[0.02218121, 0.22681584, 0.24934443, 0.67208359, 0.90130727],
        [0.55782556, 0.55782556, 0.55782556, 0.55782556, 0.55782556],
        [0.86598892, 0.729616  , 0.61181095, 0.59725838, 0.48564185],
        [0.65505927, 0.65505927, 0.65505927, 0.65505927, 0.65505927],
        [0.75488

In [45]:
X_mis

array([[0.08614976, 0.45792556, 0.57842989, 0.40389887, 0.56055436],
       [0.57587862, 0.60825491, 0.23541011, 0.24640224, 0.36782704],
       [       nan, 0.55782556,        nan, 0.65505927, 0.75488677],
       ...,
       [0.69710546, 0.05108624, 0.95522378, 0.62137791,        nan],
       [0.83227832, 0.78643521,        nan, 0.96580871, 0.13767796],
       [0.80699903,        nan, 0.70881685, 0.92214362, 0.42980842]])

In [44]:
X_imp

array([[0.56055436, 0.56055436, 0.56055436, 0.56055436, 0.56055436],
       [0.36782704, 0.36782704, 0.36782704, 0.36782704, 0.36782704],
       [0.75488677, 0.75488677, 0.75488677, 0.75488677, 0.75488677],
       ...,
       [0.96570798, 0.56563466, 0.65859195, 0.53446886, 0.5722103 ],
       [0.13767796, 0.13767796, 0.13767796, 0.13767796, 0.13767796],
       [0.42980842, 0.42980842, 0.42980842, 0.42980842, 0.42980842]])

In [42]:
for i in range(5):
    X_imp = tmp[:,i]
    print(np.nanmean(get_smae(X_imp, X, X_mis)))

1.43469628795332
1.3916951616393543
1.2025055237548579
1.1926284839285006
1.431248921506579
