In [66]:
import numpy as np
import pyvinecopulib as pv
from vcimpute.helper_datagen import make_complete_data_matrix, mask_MCAR
from vcimpute.helper_mdp import all_mdps_idx

In [67]:
X = make_complete_data_matrix(1000, 10, 'gaussian', seed=42)

In [68]:
X_mask = mask_MCAR(X, 'general', 0.2, seed=42)

In [69]:
all_mdps_idx(X_mask)

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 9, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 8, 0, 0],
       [1, 2, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=uint64)

In [16]:
all_mdps_idx(X_mask)[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint64)

In [25]:
controls = pv.FitControlsVinecop(family_set=[pv.BicopFamily.gaussian], num_threads=10)
cop = pv.Vinecop(d=10)
cop.select(X_mask, controls)

In [28]:
from vcimpute.helper_diagonalize import diagonalize_matrix

In [30]:
T = diagonalize_matrix(cop.matrix)

In [35]:
tree.contains([1,2,3])

NameError: name 'tree' is not defined

In [36]:
path = [1,2,3]

In [56]:
class Tree:
    def __init__(self, this_var):
        self.this_var = this_var
        self.children = []
        
    def add_child(self, child_var):
        self.children.append(Tree(child_var))
        
    def __eq__(self, other_var):
        return self.this_var == other_var

In [57]:
tree = Tree(0)

In [58]:
tree.add_child(5)

In [65]:
tree.children.index(5)

0

In [60]:
loc = tree
for p in path:
    

True

In [47]:
tree.children[0].nid

0

In [ ]:
for p in path:
    

In [32]:
d = 10
all_paths = []
a_paths = []
b_paths = []
for j in range(d):
    a_paths.append(T[d-j-1,j])

In [34]:
T

array([[ 4,  9, 10,  9,  7,  8,  8,  4,  4,  4],
       [ 7,  1,  7,  8,  4,  4,  4,  8,  8,  0],
       [10,  8,  4,  4,  8,  7,  7,  7,  0,  0],
       [ 6,  4,  8,  7,  2,  2,  2,  0,  0,  0],
       [ 8,  7,  2,  2,  9,  9,  0,  0,  0,  0],
       [ 2,  2,  9, 10, 10,  0,  0,  0,  0,  0],
       [ 9, 10,  1,  1,  0,  0,  0,  0,  0,  0],
       [ 1,  6,  6,  0,  0,  0,  0,  0,  0,  0],
       [ 3,  3,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 5,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=uint64)

In [27]:
cop.matrix

array([[ 4,  9,  9, 10,  8,  8,  7,  4,  8,  8],
       [ 7,  1,  8,  7,  4,  4,  4,  8,  4,  0],
       [10,  8,  4,  4,  7,  7,  8,  7,  0,  0],
       [ 6,  4,  7,  8,  2, 10, 10,  0,  0,  0],
       [ 8,  7,  2,  2, 10,  2,  0,  0,  0,  0],
       [ 2,  2, 10,  9,  9,  0,  0,  0,  0,  0],
       [ 9, 10,  6,  6,  0,  0,  0,  0,  0,  0],
       [ 1,  6,  1,  0,  0,  0,  0,  0,  0,  0],
       [ 3,  3,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 5,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=uint64)

In [21]:
np.unique(list(map(lambda x: set(filter(lambda y: y !=0, x)), all_mdps_idx(X_mask))))

array([set(), {9}, {10, 5}, {2}, {3}, {10}, {2, 5, 6}, {9}, {7}, {2}, {4},
       {2, 7}, {1}, {1, 3, 5}, {9}, {10, 5, 6}, {2, 5, 6}, {1}, {9},
       {9, 2}, {1, 9}, {2, 3}, {1}, {5}, {9}, {6}, {8, 9}, {8, 2, 3, 5},
       {9}, {8}, {1, 10}, {6}, {10}, {3, 6, 7}, {10, 5}, {6, 7},
       {2, 10, 6}, {7}, {9}, {4}, {9, 6}, {9, 2, 3, 6}, {4}, {8, 3, 7},
       {6, 7}, {2, 3}, {10, 5}, {3, 4}, {9}, {2, 4}, {8}, {10, 6}, {2, 7},
       {8, 3, 4}, {10}, {1}, {4, 5}, {8, 4, 5, 7}, {8, 2, 4, 6}, {9},
       {8, 5}, {8, 4}, {10}, {8}, {10}, {10, 3, 5}, {2}, {10}, {1},
       {3, 5}, {4, 5, 7}, {3, 5}, {8, 4}, {1}, {8, 1, 2, 5}, {4}, {10},
       {9, 2, 4}, {1}, {8, 1}, {10}, {2, 3}, {1, 5}, {8, 1, 10, 3},
       {1, 6}, {2}, {1, 2}, {10}, {3, 5}, {10, 3}, {2}, {7}, {2, 10, 7},
       {3}, {4, 7}, {2, 3, 4, 5, 6, 9}, {8, 9, 6}, {9, 10}, {1, 3, 9},
       {1, 2, 3, 9}, {4}, {1}, {7}, {4}, {3, 6}, {2, 6}, {9, 3}, {1}, {2},
       {4}, {10, 4}, {1}, {1, 6}, {3, 5}, {3, 4, 5}, {2, 3, 5, 6},
       