In [19]:
import numpy as np
import pyvinecopulib as pv

In [ ]:
T

In [ ]:
def adhoc_patterns(T):
    pass

In [ ]:
T2 = np.zeros(shape=(d, d), dtype=np.uint64)
for j in range(d-1):
    for i in range(d-j-1):
        T2[i,j] = cop.structure.struct_array(i, j, natural_order=True)
for j in range(d):
    T2[d-j-1,j] = 1++j
    

In [20]:
structure = pv.RVineStructure(d=10)
cop = pv.Vinecop(structure)
T = cop.matrix

In [ ]:

j=0
T2[d-j-1,0] = T[d-j-1,0]
T2[d-j-2,0] = T[d-j-2,0]

In [ ]:
T

In [ ]:
structure = pv.RVin

In [38]:
bicop =pv.Bicop(family=pv.BicopFamily.gaussian, parameters=[0])

In [25]:
def is_diagonal(T):
    d = T.shape[1]
    diagonal = True
    for j in range(d-1):
        diagonal &= T[d-j-2, j] == T[d-j-2, j+1]
    return diagonal

In [44]:
bicop.parameters[0])

array([0.])

In [ ]:
bicop.

In [46]:
bicop.family

<BicopFamily.gaussian: 1>

In [45]:
pv.Bicop(family=pv.BicopFamily.gaussian, parameters=bicop.parameters)

<pyvinecopulib.Bicop>
Gaussian, parameters = 0

In [35]:
cop.get_pair_copula(0,1).parameters

array([], shape=(0, 0), dtype=float64)

In [ ]:
pv.Vinecop(pv.RVineStructure(T2))

In [ ]:
cop

In [ ]:
for k in range(d-j-1):
    print(, )

In [ ]:
T2

In [ ]:
for j in range(1,d-1):
    if T2[d-j-1,j] != T2[d-j-1,j-1]:
        T2[d-j-1,j] = T2[d-j-1,j-1]
        T2[d-j-2,j] = T[d-j-1,j]
    
    for k in range(d-j-2):
        assert T2[k,j]==0
        T2[k, j] = find(T2[d-j-1,j], k, ced, cing)
T2[0,d-1] = T2[0,d-2]

In [ ]:
structure.

In [ ]:
structure.struct_array(0,6)

In [59]:
structure = pv.RVineStructure(d=4)

In [62]:
pv.Vinecop(structure).matrix

array([[2, 3, 4, 4],
       [3, 4, 3, 0],
       [4, 2, 0, 0],
       [1, 0, 0, 0]], dtype=uint64)

In [60]:
structure

<pyvinecopulib.RVineStructure>
2 3 4 4 
3 4 3 
4 2 
1 

In [55]:
T =np.array([[2, 3, 4, 5, 6, 6],
       [3, 4, 5, 6, 5, 0],
       [4, 5, 6, 4, 0, 0],
       [5, 6, 3, 0, 0, 0],
       [6, 2, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0]], dtype=np.uint64)

In [53]:
pv.Vinecop(structure).matrix

array([[2, 3, 4, 5, 6, 6],
       [3, 4, 5, 6, 5, 0],
       [4, 5, 6, 4, 0, 0],
       [5, 6, 3, 0, 0, 0],
       [6, 2, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0]], dtype=uint64)

In [56]:
diagonalize_matrix(T)

array([[2, 5, 3, 4, 4, 4],
       [3, 4, 4, 3, 3, 0],
       [4, 3, 5, 5, 0, 0],
       [5, 2, 2, 0, 0, 0],
       [6, 6, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0]], dtype=uint64)

In [ ]:
pv.RVineStructure(np.array([
[2, 4, 3, 3, 3],
[3, 3, 4, 4, 0],
[4, 2, 2, 0, 0],
[5, 5, 0, 0, 0],
[1, 0, 0, 0, 0]
], dtype=np.uint64))

In [ ]:
T

In [ ]:
cop

In [ ]:
d = T.shape[1]

In [27]:
is_diagonal(diagonalize_matrix(T))

True

In [ ]:
ced, cing, _ = get_ced_cing(T)
T2 = np.zeros(shape=(d,d),dtype=np.uint64)

j=0
T2[d-j-1,0] = T[d-j-1,0]
T2[d-j-2,0] = T[d-j-2,1]

for k in range(d-j-2):
    assert T2[k,j]==0
    T2[k, j] = find(T2[d-j-1,j], k, ced, cing)


for j in range(1,d-1):
    if T2[d-j-1,j] != T2[d-j-1,j-1]:
        T2[d-j-1,j] = T2[d-j-1,j-1]
        T2[d-j-2,j] = T[d-j-1,j]
    
    for k in range(d-j-2):
        assert T2[k,j]==0
        T2[k, j] = find(T2[d-j-1,j], k, ced, cing)
T2[0,d-1] = T2[0,d-2]