In [3]:
import numpy as np
import pandas as pd
import pyvinecopulib as pv

from gcimpute.gaussian_copula import GaussianCopula
from gcimpute.helper_evaluation import get_smae
from gcimpute.helper_data import generate_mixed_from_gc
from gcimpute.helper_mask import mask_MCAR

In [7]:
d=10
X = generate_mixed_from_gc(var_types={'cont': list(range(d))})

In [14]:
X_mask = mask_MCAR(X, 0.2)

In [25]:
from vcimpute.helper_mdp import all_mdps, count_missing_by_col, count_missing_by_row, sort_mdps_by_increasing_missing_vars

In [26]:
count_missing_by_row(sort_mdps_by_increasing_missing_vars(X_mask))

array([1, 3, 2, ..., 1, 3, 3])

In [29]:
set(sorted(count_missing_by_row(X_mask)))

{0, 1, 2, 3, 4, 5, 6, 7, 8}

In [21]:
count_missing_by_col(X_mask)

array([408, 368, 405, 374, 422, 428, 415, 386, 415, 379])

In [18]:
all_mdps(X_mask)

array([[False, False, False, ..., False, False,  True],
       [False, False, False, ..., False,  True, False],
       [False, False, False, ..., False,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True, False],
       [ True,  True,  True, ..., False, False,  True],
       [ True,  True,  True, ...,  True, False,  True]])