In [1]:
from IPython.display import display
import numpy as np
import pandas as pd
import pyvinecopulib as pv

In [2]:
n = 1000
d = 3
structure = np.matrix([[2,2,2],[3,3,np.nan],[1,np.nan,np.nan]])
pair_copulas = [[
    pv.Bicop(family=pv.BicopFamily.gaussian, parameters=[[.75]]),
    pv.Bicop(family=pv.BicopFamily.gaussian, parameters=[[.25]])
],
[
    pv.Bicop(family=pv.BicopFamily.gaussian, parameters=[[.25]])
]]
cop = pv.Vinecop(structure, pair_copulas)
U = cop.simulate(n=n)

In [3]:
np.corrcoef(U.T)

array([[1.        , 0.74683505, 0.30642501],
       [0.74683505, 1.        , 0.25333083],
       [0.30642501, 0.25333083, 1.        ]])

In [4]:
cop.matrix

array([[2, 2, 2],
       [3, 3, 0],
       [1, 0, 0]], dtype=uint64)

In [5]:
cop

<pyvinecopulib.Vinecop>
** Tree: 0
1,2 <-> Gaussian, parameters = 0.75
3,2 <-> Gaussian, parameters = 0.25
** Tree: 1
1,3 | 2 <-> Gaussian, parameters = 0.25

In [10]:
u1_imp = cop.get_pair_copula(0,0).hinv2(np.hstack([
    np.random.uniform(size=n)[:, None],
    U[:,1][:, None]
]))

IndentationError: unexpected indent (2888572888.py, line 2)

In [7]:
u1_imp-

array([0.25969378, 0.61501885, 0.5292442 , 0.54179813, 0.45733975,
       0.13333567, 0.14668566, 0.65606092, 0.27546649, 0.68719292,
       0.33461219, 0.84870186, 0.47869842, 0.1454145 , 0.6456408 ,
       0.54352493, 0.05810369, 0.35197678, 0.95143536, 0.81439263,
       0.48182226, 0.72699583, 0.8496973 , 0.80380494, 0.86175101,
       0.78693902, 0.26177304, 0.5584538 , 0.54374449, 0.44515366,
       0.4403859 , 0.73490325, 0.26529732, 0.41813474, 0.75739398,
       0.34905427, 0.79703319, 0.71620804, 0.84610664, 0.66676536,
       0.59463757, 0.73978592, 0.73452172, 0.40039927, 0.40771188,
       0.96805086, 0.16501472, 0.45715166, 0.77915672, 0.48180164,
       0.49273947, 0.52391869, 0.81918633, 0.73376316, 0.25838868,
       0.72782797, 0.27078143, 0.22146852, 0.62014551, 0.35621906,
       0.57729964, 0.88846473, 0.21034009, 0.45427123, 0.2973691 ,
       0.48403773, 0.69001626, 0.2105347 , 0.46654699, 0.82570454,
       0.54835246, 0.60556344, 0.5471703 , 0.42093527, 0.59956