In [9]:
import numpy as np

from vcimpute.sub_vines import remove_column, remove_inbetween
from vcimpute.util import get, get_order, get_pair_copulas, make_copula

In [2]:
cop = make_copula(5)

In [3]:
U = cop.simulate(n=1000)

In [4]:
cop.matrix

array([[5, 3, 5, 5, 5],
       [3, 5, 3, 3, 0],
       [1, 1, 1, 0, 0],
       [4, 4, 0, 0, 0],
       [2, 0, 0, 0, 0]], dtype=uint64)

In [5]:
cop.order

[2, 4, 1, 3, 5]

In [6]:
var_mis = cop.order[2]

In [7]:
missing = np.random.binomial(n=1, p=0.2, size=U.shape[0])
U_mask = np.copy(U)
u_mask = get(U_mask, var_mis)
u_mask[missing == 1] = np.nan

In [8]:
U_mask

array([[0.14491306, 0.2577841 , 0.40841315, 0.39660764, 0.50405406],
       [       nan, 0.37050758, 0.76700429, 0.64249497, 0.41668058],
       [0.96092476, 0.74023969, 0.04905787, 0.20234375, 0.53379028],
       ...,
       [0.80772651, 0.03069847, 0.65405496, 0.07157443, 0.00583926],
       [0.68356614, 0.56371734, 0.1667308 , 0.27715496, 0.51430251],
       [0.93118889, 0.94903772, 0.77918603, 0.91035932, 0.83103296]])

NameError: name 'T_tmp' is not defined

In [11]:
T = cop.matrix
pair_copulas = get_pair_copulas(cop)
d = T.shape[0]

T_tmp, pair_copulas_tmp = T, pair_copulas
out1 = []
out2 = []
for j in range(d):
    d_tmp = T_tmp.shape[0]
    if (var_mis == T_tmp[d_tmp-1, 0]) or (var_mis == T_tmp[d_tmp-2, 0]):
        order_tmp = get_order(T_tmp)
        if order_tmp not in out2:
            out1.append((T_tmp, pair_copulas_tmp))
            out2.append(order_tmp)
    T_tmp, pair_copulas_tmp = remove_column(T, pair_copulas, var_mis, j)

In [12]:
T

array([[5, 3, 5, 5, 5],
       [3, 5, 3, 3, 0],
       [1, 1, 1, 0, 0],
       [4, 4, 0, 0, 0],
       [2, 0, 0, 0, 0]], dtype=uint64)

In [13]:
a_lst = [[0,1,2], [2,1,0]]
e = [0,1,2]

In [ ]:
d_tmp=5

In [15]:
out1

[(array([[3, 5, 5, 5],
         [5, 3, 3, 0],
         [1, 1, 0, 0],
         [4, 0, 0, 0]], dtype=uint64),
  [[<pyvinecopulib.Bicop>
    Gaussian, parameters = 0.681383,
    <pyvinecopulib.Bicop>
    Gaussian, parameters = 0.0259017,
    <pyvinecopulib.Bicop>
    Gaussian, parameters = 0.025886],
   [<pyvinecopulib.Bicop>
    Gaussian, parameters = 0.99,
    <pyvinecopulib.Bicop>
    Gaussian, parameters = 0.416215],
   [<pyvinecopulib.Bicop>
    Gaussian, parameters = 0.717181]]),
 (array([[5, 5, 5, 5],
         [3, 3, 3, 0],
         [1, 1, 0, 0],
         [2, 0, 0, 0]], dtype=uint64),
  [[<pyvinecopulib.Bicop>
    Gaussian, parameters = 0.829937,
    <pyvinecopulib.Bicop>
    Gaussian, parameters = 0.0259017,
    <pyvinecopulib.Bicop>
    Gaussian, parameters = 0.025886],
   [<pyvinecopulib.Bicop>
    Gaussian, parameters = 0.407694,
    <pyvinecopulib.Bicop>
    Gaussian, parameters = 0.416215],
   [<pyvinecopulib.Bicop>
    Gaussian, parameters = 0.875737]])]

In [ ]:
# apply to T (d=5,j=0)
# apply to T (d=5,j=1) if in cond set, but no change, then stop
# 


In [ ]:
e in a_lst

In [ ]:
out