In [16]:
from copy import deepcopy

import numpy as np
import pandas as pd

import pyvinecopulib as pv
from vcimpute.generate_data import make_complete_data_matrix, mask_MCAR
from vcimpute.util import make_triangular_array
from vcimpute.sub_vines import remove_column, remove_inbetween

# def remove_inbetween(T_in, pair_copulas_in, var_mis, j):
# def remove_column(T_in, pair_copulas_in, var_mis, j):

In [17]:
class VineCopFit:
    pass

In [18]:
X = make_complete_data_matrix(n=1000,d=5,copula_type='gaussian')
X_mis = mask_MCAR(X, d_mis=2, mask_fraction=.2, monotonic_missingness=True)
controls = pv.FitControlsVinecop(family_set=[pv.BicopFamily.gaussian], num_threads=10)
cop = pv.Vinecop(data=X_mis, controls=controls)

In [40]:
var_mis = 4
d = 5
T_tmp = T
pcs_tmp = pcs
for j in range(d-2):
    if (T_tmp[d-2,0] == var_mis) or (T_tmp[d-1,0] == var_mis):
        continue
    T_tmp0, pcs_tmp0 = remove_inbetween(T_tmp, pcs_tmp, var_mis, j)
    T_tmp0, pcs_tmp0 = remove_inbetween(T_tmp, pcs_tmp, var_mis, j)
    break

In [44]:
T_tmp[d-2,0]

2

SyntaxError: invalid syntax (2091818123.py, line 1)

In [41]:
remove_inbetween(T_tmp, pcs_tmp, var_mis, 0)

(array([[1, 4, 4],
        [4, 1, 0],
        [5, 0, 0]], dtype=uint64),
 [[<pyvinecopulib.Bicop>
   Gaussian, parameters = -0.560197,
   <pyvinecopulib.Bicop>
   Gaussian, parameters = 0.431026],
  [<pyvinecopulib.Bicop>
   Gaussian, parameters = 0.199507]])

In [8]:
T2, pcs2 = remove_inbetween(T, pcs, 4, 0)

In [15]:
remove_inbetween(T2, pcs2, 4, 1)

(array([[1, 4, 4],
        [4, 1, 0],
        [5, 0, 0]], dtype=uint64),
 [[<pyvinecopulib.Bicop>
   Gaussian, parameters = -0.575671,
   <pyvinecopulib.Bicop>
   Gaussian, parameters = 0.435853],
  [<pyvinecopulib.Bicop>
   Gaussian, parameters = 0.173239]])

In [7]:
remove_column(T, pcs, 4, 0)

(array([[4, 3, 4, 4],
        [3, 4, 3, 0],
        [2, 2, 0, 0],
        [1, 0, 0, 0]], dtype=uint64),
 [[<pyvinecopulib.Bicop>
   Gaussian, parameters = 0.435853,
   <pyvinecopulib.Bicop>
   Gaussian, parameters = -0.832617,
   <pyvinecopulib.Bicop>
   Gaussian, parameters = 0.464156],
  [<pyvinecopulib.Bicop>
   Gaussian, parameters = -0.222012,
   <pyvinecopulib.Bicop>
   Gaussian, parameters = 0.268009],
  [<pyvinecopulib.Bicop>
   Gaussian, parameters = -0.550512]])

In [ ]:
# run above functions iteratively