In [83]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from vcimpute.helper_datagen import make_complete_data_matrix, mask_MCAR
from vcimpute.helper_mdp import all_mdps, all_miss_vars, count_missing_by_col, sort_miss_vars_by_increasing_miss_vars, count_missing_by_row

In [3]:
seed = 0

In [58]:
X = make_complete_data_matrix(1000, 3, 'gaussian', seed)

In [9]:
X_mask = mask_MCAR(X, 'univariate', 0.1, seed)

In [29]:
X_mask = mask_MCAR(X, 'monotone', 0.1, seed, n_cols=5)

In [30]:
# monotone, increase number of missing cols

In [31]:
count_missing_by_col(X_mask)

array([  0,   0, 105, 107,  82, 108,   0,  98,   0,   0])

In [34]:
X_mask = mask_MCAR(X, 'general', 0.1, seed)

In [35]:
all_miss_vars(X_mask)

array([[ 0,  0,  0, ...,  0,  0, 10],
       [ 0,  0,  0, ...,  0,  9,  0],
       [ 0,  0,  0, ...,  0,  9, 10],
       ...,
       [ 1,  2,  0, ...,  0,  0,  0],
       [ 1,  2,  0, ...,  0,  0,  0],
       [ 1,  2,  3, ...,  0,  0,  0]], dtype=uint64)

In [41]:
len(all_mdps(X_mask))

114

In [40]:
count_missing_by_col(X_mask)

array([101,  95,  98,  94, 109,  91, 102, 110,  96, 104])

array([[0.51877747, 0.49952267, 0.47961353, 0.28588137, 0.38465868],
       [0.08183934, 0.38673747, 0.79930499, 0.15599889, 0.66666019],
       [0.70914757, 0.70236217, 0.7355197 , 0.97272347, 0.77975731],
       ...,
       [0.53313907, 0.00853822, 0.99027109, 0.83923679, 0.20904907],
       [0.69901654, 0.87648763, 0.09367378, 0.12939391, 0.21235358],
       [0.72902856, 0.67775185, 0.66133448, 0.75687729, 0.40727539]])

In [65]:
m = 0
for i in range(1,5):
    m += comb(5,i)

In [ ]:
# mdps
# univariate - 1 
# monotonic - # mdps= 1 per n cols
# general - # mdp

In [ ]:
keep track of mdps
keep track of number of models fit
elapsed time
accuracy

In [66]:
m

30.0

In [62]:
numpy 

TypeError: 'int' object is not iterable

In [61]:
all_miss_vars(X_mask)

array([[0, 0, 3],
       [0, 2, 0],
       [0, 2, 3],
       [1, 0, 0],
       [1, 0, 3],
       [1, 2, 0]], dtype=uint64)

In [60]:
sort_miss_vars_by_increasing_miss_vars(all_miss_vars(X_mask))

[array([0, 0, 3], dtype=object),
 array([0, 2, 0], dtype=object),
 array([0, 2, 3], dtype=object),
 array([1, 0, 0], dtype=object),
 array([1, 0, 3], dtype=object),
 array([1, 2, 0], dtype=object)]

In [68]:
lst = pd.read_pickle('/Users/nshah/work/vcimpute/vcimpute/scripts/experiment3_univariate.pkl')

In [74]:
df = pd.DataFrame([e for a_lst in lst for e in a_lst],  columns=['method', 'seed', 'n_fits', 'n_sims', 'smae', 'elapsed', 'bias'])

In [77]:
df[df['method'] == 'copfit']

method  seed  n_fits  n_sims      smae     elapsed      bias
2   copfit     0       1       3  0.508771  5968564000  0.007761
6   copfit     1       1       2  0.905874  6140127000  0.005199
10  copfit     2       1       3  0.378894  5950202000  0.005311
14  copfit     3       1       3  0.521822  5802320000  0.007491
18  copfit     4       1       9  0.682469  5321969000  0.010471
22  copfit     5       1       8  0.910154  4894128000  0.011464
26  copfit     6       1       2  0.696030  6286318000  0.005857
30  copfit     7       1       7  0.581230  6079180000  0.007688
34  copfit     8       1       5  0.260888  5827904000  0.005287
38  copfit     9       1       2  0.766025  6408760000  0.011374

{0: 206, 1: 450, 2: 344}

In [78]:
df[df['method'] == 'mdpfit']

method  seed  n_fits  n_sims      smae      elapsed      bias
1   mdpfit     0       4       1  0.199461  21047377000  0.001875
5   mdpfit     1       4       1  0.870553  21116758000  0.009937
9   mdpfit     2       4       1  0.185286  20934866000  0.003375
13  mdpfit     3       4       1  0.180836  21145018000  0.001037
17  mdpfit     4       4       1  0.115031  21234131000  0.000756
21  mdpfit     5       4       1  0.142478  21121953000  0.001532
25  mdpfit     6       4       1  0.891738  21639493000  0.011734
29  mdpfit     7       4       1  0.440748  20881752000  0.006271
33  mdpfit     8       4       1  0.078850  21910763000  0.000661
37  mdpfit     9       4       1  0.863943  21826632000  0.012968