In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from vcimpute.helper_datagen import make_complete_data_matrix, mask_MCAR
from vcimpute.helper_mdp import all_mdps, all_miss_vars, count_missing_by_col, sort_miss_vars_by_increasing_miss_vars, count_missing_by_row

In [3]:
seed = 0

In [8]:
fname = '/Users/nshah/work/vcimpute/vcimpute/scripts/experiment3_general.pkl'
df = pd.DataFrame(
    [e for lst in pd.read_pickle(fname) for e in lst],
    columns=['method', 'seed', 'n_fits', 'n_sims', 'n_mdps', 'n_cc', 'smae', 'elapsed', 'bias']
)

In [27]:
df['elapsed_s'] = df['elapsed']/1e9
df['smae'] =df['smae'].apply(np.nanmean)

In [20]:
df[df['method']=='gcimpute']['n_cc']

0     583
4     583
8     583
12    583
16    583
20    583
24    583
28    583
32    583
36    583
Name: n_cc, dtype: int64

In [14]:
df.groupby(['method', 'n_fits'])['elapsed_s'].sum()

method    n_fits
copfit    1          88.059376
copreg    40        448.443953
gcimpute  1           2.567604
mdpfit    15         18.992549
          18        113.752280
          19         24.647969
          20         25.257256
          23         58.165537
Name: elapsed_s, dtype: float64

In [17]:
df.groupby(['method', 'n_fits','n_sims'])['elapsed_s'].mean()

method    n_fits  n_sims
copfit    1       78         8.449854
                  79         8.542310
                  81         8.677031
                  84         8.946438
                  85         8.910556
                  87         9.016844
copreg    40      40        44.844395
gcimpute  1       1          0.256760
mdpfit    15      20        18.992549
          18      20        22.750456
          19      20        24.647969
          20      20        25.257256
          23      20        29.082769
Name: elapsed_s, dtype: float64

In [35]:
13*100/60

21.666666666666668

In [33]:
df['elapsed'].sum()/1e9/60

12.998108733333334

In [31]:
pd.set_option('display.float_format', '{:,.2f}'.format)
df.groupby('method')[['bias','smae']].mean()

bias  smae
method              
copfit    0.03  0.85
copreg    0.02  0.79
gcimpute  0.03  0.58
mdpfit    0.02  0.84

In [12]:
df.groupby('method')['elapsed_s'].mean()

method
copfit       8.805938
copreg      44.844395
gcimpute     0.256760
mdpfit      24.081559
Name: elapsed_s, dtype: float64

In [141]:
X = make_complete_data_matrix(1000, 5, 'gaussian', seed)

In [9]:
X_mask = mask_MCAR(X, 'univariate', 0.1, seed)

In [29]:
X_mask = mask_MCAR(X, 'monotone', 0.1, seed, n_cols=5)

In [30]:
# monotone, increase number of missing cols

In [31]:
count_missing_by_col(X_mask)

array([  0,   0, 105, 107,  82, 108,   0,  98,   0,   0])

In [142]:
X_mask = mask_MCAR(X, 'general', 0.1, seed)

In [89]:
from scipy.special import comb

In [136]:
d = 5

In [137]:
m = 0
for i in range(1,d):
    m += comb(d,i)
m

30.0

In [140]:
.1*(1000*5)

500.0

In [138]:
# mdps
# univariate - 1 
# monotonic - # mdps= 1 per n cols
# general - # mdp

In [139]:
254*24/60

101.6

In [125]:
keep track of mdps
keep track of number of models fit
elapsed time
accuracy

SyntaxError: invalid syntax (2019850167.py, line 1)

In [66]:
m

30.0

In [62]:
numpy 

TypeError: 'int' object is not iterable

In [61]:
all_miss_vars(X_mask)

array([[0, 0, 3],
       [0, 2, 0],
       [0, 2, 3],
       [1, 0, 0],
       [1, 0, 3],
       [1, 2, 0]], dtype=uint64)

In [60]:
sort_miss_vars_by_increasing_miss_vars(all_miss_vars(X_mask))

[array([0, 0, 3], dtype=object),
 array([0, 2, 0], dtype=object),
 array([0, 2, 3], dtype=object),
 array([1, 0, 0], dtype=object),
 array([1, 0, 3], dtype=object),
 array([1, 2, 0], dtype=object)]

In [68]:
lst = pd.read_pickle('/Users/nshah/work/vcimpute/vcimpute/scripts/experiment3_univariate.pkl')

In [74]:
df = pd.DataFrame([e for a_lst in lst for e in a_lst],  columns=['method', 'seed', 'n_fits', 'n_sims', 'smae', 'elapsed', 'bias'])

In [77]:
df[df['method'] == 'copfit']

method  seed  n_fits  n_sims      smae     elapsed      bias
2   copfit     0       1       3  0.508771  5968564000  0.007761
6   copfit     1       1       2  0.905874  6140127000  0.005199
10  copfit     2       1       3  0.378894  5950202000  0.005311
14  copfit     3       1       3  0.521822  5802320000  0.007491
18  copfit     4       1       9  0.682469  5321969000  0.010471
22  copfit     5       1       8  0.910154  4894128000  0.011464
26  copfit     6       1       2  0.696030  6286318000  0.005857
30  copfit     7       1       7  0.581230  6079180000  0.007688
34  copfit     8       1       5  0.260888  5827904000  0.005287
38  copfit     9       1       2  0.766025  6408760000  0.011374

In [78]:
df[df['method'] == 'mdpfit']

method  seed  n_fits  n_sims      smae      elapsed      bias
1   mdpfit     0       4       1  0.199461  21047377000  0.001875
5   mdpfit     1       4       1  0.870553  21116758000  0.009937
9   mdpfit     2       4       1  0.185286  20934866000  0.003375
13  mdpfit     3       4       1  0.180836  21145018000  0.001037
17  mdpfit     4       4       1  0.115031  21234131000  0.000756
21  mdpfit     5       4       1  0.142478  21121953000  0.001532
25  mdpfit     6       4       1  0.891738  21639493000  0.011734
29  mdpfit     7       4       1  0.440748  20881752000  0.006271
33  mdpfit     8       4       1  0.078850  21910763000  0.000661
37  mdpfit     9       4       1  0.863943  21826632000  0.012968