In [1]:
import numpy as np
import pyvinecopulib as pv
from vcimpute.helper_datagen import make_complete_data_matrix, mask_MCAR
from vcimpute.helper_mdp import sort_miss_vars_by_increasing_miss_vars, mdp_coords, old_to_new
from vcimpute.sakuth import MdpFit
from vcimpute.utils import vfunc

seed = 22
d = 5

X = make_complete_data_matrix(1000, d, 'gaussian', seed=seed)
X_mask = mask_MCAR(X, 'general', 0.2, seed=seed)

model = MdpFit('gaussian', 10, seed)
model.fit_transform(X_mask)

1000
538
206
164
58


array([[0.931     , 0.41      , 0.551     , 0.986     , 0.132     ],
       [0.509     , 0.029     , 0.977     , 0.55      , 0.234     ],
       [0.04214665, 0.102     , 0.94306832, 0.034     , 0.647     ],
       ...,
       [0.759     , 0.292     , 0.799     , 0.809     , 0.26725225],
       [0.943     , 0.007     , 0.9995664 , 0.954     , 0.333     ],
       [0.858     , 0.91570707, 0.175     , 0.791     , 0.88      ]])

In [2]:
from gcimpute.helper_evaluation import get_smae

In [4]:
get_smae(model.X_imp, X, X_mask)

array([0.86285634, 0.78212362, 0.83783131, 0.96858591, 1.15793174])

In [5]:
from gcimpute.gaussian_copula import GaussianCopula

In [11]:
get_smae(GaussianCopula().fit_transform(X_mask), X, X_mask)

array([0.65013183, 0.49234653, 0.435378  , 0.70059486, 0.80425735])