In [2]:
import numpy as np
import pyvinecopulib as pv
from vcimpute.helper_datagen import make_complete_data_matrix, mask_MCAR
from vcimpute.helper_mdp import sort_miss_vars_by_increasing_miss_vars, mdp_coords, old_to_new
from vcimpute.sakuth import MdpFit
from vcimpute.utils import vfunc

seed = 42
d = 10

X = make_complete_data_matrix(1000, d, 'gaussian', seed=seed)
X_mask = mask_MCAR(X, 'general', 0.05, seed=seed)

model = MdpFit('gaussian', 10, seed)
model.fit_transform(X_mask)

500
399
358
331
295
246
163
120
112
110
106
104
85
73
67
61
55
43
41
35
26
22
16
14
10
7
4


array([[0.408, 0.595, 0.954, ..., 0.25 , 0.121, 0.85 ],
       [0.185, 0.885, 0.72 , ..., 0.844, 0.475, 0.367],
       [0.486, 0.461, 0.742, ..., 0.449, 0.293, 0.902],
       ...,
       [0.574, 0.079, 0.433, ..., 0.913, 0.723, 0.438],
       [0.898, 0.802, 0.034, ..., 0.597, 0.925, 0.186],
       [0.271, 0.342, 0.805, ..., 0.048, 0.012, 0.248]])

In [3]:
from gcimpute.helper_evaluation import get_smae

In [4]:
get_smae(model.X_imp, X, X_mask)

array([0.58004181, 0.35174696, 0.70830291, 0.3679416 , 0.91698463,
       0.54130891, 0.36443629, 0.23973899, 0.43112191, 0.7060708 ])

In [7]:
np.mean(get_smae(model.X_imp, X, X_mask))

0.5207694809523166

In [5]:
from gcimpute.gaussian_copula import GaussianCopula

In [6]:
get_smae(GaussianCopula().fit_transform(X_mask), X, X_mask)

array([0.41412568, 0.19559173, 0.50286364, 0.16604731, 0.5560762 ,
       0.2861729 , 0.16644247, 0.12731047, 0.24059434, 0.40247051])

In [8]:
np.mean(get_smae(GaussianCopula().fit_transform(X_mask), X, X_mask))

0.305769524383335