In [91]:
import numpy as np
import pandas as pd
import pyvinecopulib as pv

In [92]:
n = 1000
d = 4
p = 0.2

structure = pv.RVineStructure.simulate(d)

pair_copulas = []
for j in range(d - 1):
    tmp = []
    pair_copulas.append(tmp)
    for _ in range(d - j - 1):
        rho = np.minimum(np.maximum(np.random.beta(1, 0.75), 0.01), 0.99)
        tmp.append(pv.Bicop(family=pv.BicopFamily.gaussian, parameters=[[rho]]))

cop = pv.Vinecop(structure, pair_copulas)

U = cop.simulate(n=n, seeds=list(1 + np.arange(d)))

In [93]:
cop

<pyvinecopulib.Vinecop>
** Tree: 0
3,2 <-> Gaussian, parameters = 0.184723
4,2 <-> Gaussian, parameters = 0.231041
1,2 <-> Gaussian, parameters = 0.938975
** Tree: 1
3,1 | 2 <-> Gaussian, parameters = 0.371466
4,1 | 2 <-> Gaussian, parameters = 0.694321
** Tree: 2
3,4 | 1,2 <-> Gaussian, parameters = 0.765872

In [95]:
cop.matrix

array([[2, 2, 2, 2],
       [1, 1, 1, 0],
       [4, 4, 0, 0],
       [3, 0, 0, 0]], dtype=uint64)

In [96]:
controls = pv.FitControlsVinecop(family_set=[pv.BicopFamily.gaussian])
cop2 = pv.Vinecop(data=U, controls=controls)
cop2

<pyvinecopulib.Vinecop>
** Tree: 0
2,1 <-> Gaussian, parameters = 0.937197
1,4 <-> Gaussian, parameters = 0.46644
3,4 <-> Gaussian, parameters = 0.801543
** Tree: 1
2,4 | 1 <-> Gaussian, parameters = -0.638933
1,3 | 4 <-> Gaussian, parameters = -0.0845487
** Tree: 2
2,3 | 4,1 <-> Gaussian, parameters = 0.31807

In [97]:
cop2.matrix

array([[1, 4, 4, 4],
       [4, 3, 3, 0],
       [3, 1, 0, 0],
       [2, 0, 0, 0]], dtype=uint64)

In [100]:
cop3 = pv.Vinecop(data=U[:,1:], controls=controls)

In [101]:
cop3

<pyvinecopulib.Vinecop>
** Tree: 0
1,3 <-> Gaussian, parameters = 0.240044
2,3 <-> Gaussian, parameters = 0.801543
** Tree: 1
1,2 | 3 <-> Gaussian, parameters = 0.00656395

In [104]:
cop3.matrix

array([[3, 3, 3],
       [2, 2, 0],
       [1, 0, 0]], dtype=uint64)

In [102]:
controls2 = pv.FitControlsBicop(family_set=[pv.BicopFamily.gaussian])


In [103]:
bcop = pv.Bicop(data=U[:,[1,3]], controls=controls2)
bcop

<pyvinecopulib.Bicop>
Gaussian, parameters = 0.240044

In [105]:
# identify variable to impute
# fit vine on remaining columns
# identify valid expansions of the vine matrix
# fit bicops from bottom up (using pseudo obs. from h-funcs)
# impute

# cop fit, fit using sub copulas (delete variables in various orders use prev algo to fit)